-- Sinh bởi scripts/skill-meta-sql.mjs — đừng sửa tay, chạy lại script.
insert into public.skill_meta (skill_id, branch, branch_name, tier, kind, name) values
  ('cn1', 'congnhan', 'Công Nhân Ưu Tú', 1, 'passive', 'Nhặt Tiền Rơi'),
  ('cn2a', 'congnhan', 'Công Nhân Ưu Tú', 2, 'passive', 'Tăng Ca'),
  ('cn2b', 'congnhan', 'Công Nhân Ưu Tú', 2, 'passive', 'Công Đoàn'),
  ('cn3', 'congnhan', 'Công Nhân Ưu Tú', 3, 'passive', 'Thâm Niên'),
  ('cnU', 'congnhan', 'Công Nhân Ưu Tú', 4, 'passive', 'Liên Đoàn Lao Động'),
  ('cnV', 'congnhan', 'Công Nhân Ưu Tú', 4, 'passive', 'Bảo Hiểm Xã Hội'),
  ('cnX1', 'congnhan', 'Công Nhân Ưu Tú', 3, 'passive', 'Lão Làng'),
  ('cnX2', 'congnhan', 'Công Nhân Ưu Tú', 2, 'passive', 'Khách Quen Nhà Đá'),
  ('cnS1', 'congnhan', 'Công Nhân Ưu Tú', 3, 'passive', 'Bảo Hộ Lao Động'),
  ('cnS2', 'congnhan', 'Công Nhân Ưu Tú', 3, 'passive', 'Ở Tù Cho Lành'),
  ('dh1', 'duhanh', 'Nhà Du Hành', 1, 'passive', 'Vé Tháng'),
  ('dh2a', 'duhanh', 'Nhà Du Hành', 2, 'active', 'Tàu Tốc Hành'),
  ('dh2b', 'duhanh', 'Nhà Du Hành', 2, 'passive', 'Về Nhà'),
  ('dh3', 'duhanh', 'Nhà Du Hành', 3, 'active', 'Quay Đầu'),
  ('dhU', 'duhanh', 'Nhà Du Hành', 4, 'active', 'Chuyến Tàu Xuyên Việt'),
  ('dhV', 'duhanh', 'Nhà Du Hành', 4, 'passive', 'Trạm Thu Phí BOT'),
  ('dhX1', 'duhanh', 'Nhà Du Hành', 3, 'passive', 'Hai Ngón'),
  ('dhX2', 'duhanh', 'Nhà Du Hành', 2, 'passive', 'Phượt Thủ'),
  ('dhS1', 'duhanh', 'Nhà Du Hành', 3, 'active', 'Xe Đạp'),
  ('dhS2', 'duhanh', 'Nhà Du Hành', 3, 'passive', 'Dẫn Tour'),
  ('dd1', 'doden', 'Tay Chơi Đỏ Đen', 1, 'passive', 'Chẵn Lẻ'),
  ('dd2a', 'doden', 'Tay Chơi Đỏ Đen', 2, 'active', 'Cược Chẵn Lẻ'),
  ('dd2b', 'doden', 'Tay Chơi Đỏ Đen', 2, 'passive', 'Đôi Hên'),
  ('dd3', 'doden', 'Tay Chơi Đỏ Đen', 3, 'active', 'Xí Ngầu Gian'),
  ('ddU', 'doden', 'Tay Chơi Đỏ Đen', 4, 'active', 'Tất Tay'),
  ('ddV', 'doden', 'Tay Chơi Đỏ Đen', 4, 'active', 'Xổ Số Kiến Thiết'),
  ('ddX1', 'doden', 'Tay Chơi Đỏ Đen', 3, 'passive', 'Thần Tài Xỉu'),
  ('ddX2', 'doden', 'Tay Chơi Đỏ Đen', 2, 'passive', 'Con Bạc Hoàn Lương'),
  ('ddS1', 'doden', 'Tay Chơi Đỏ Đen', 3, 'passive', 'Bài Tẩy'),
  ('ddS2', 'doden', 'Tay Chơi Đỏ Đen', 3, 'active', 'Cò Quay Lương'),
  ('dcS1', 'dauco', 'Nhà Đầu Cơ', 1, 'active', 'Nhặt Hàng Thừa'),
  ('dc2a', 'dauco', 'Nhà Đầu Cơ', 2, 'passive', 'Cò Đất'),
  ('dc2b', 'dauco', 'Nhà Đầu Cơ', 2, 'passive', 'Thầu Vật Liệu'),
  ('dc3', 'dauco', 'Nhà Đầu Cơ', 3, 'active', 'Thâu Tóm'),
  ('dcU', 'dauco', 'Nhà Đầu Cơ', 4, 'passive', 'Cơn Sốt Đất'),
  ('dcV', 'dauco', 'Nhà Đầu Cơ', 4, 'active', 'Siết Nợ'),
  ('dcX1', 'dauco', 'Nhà Đầu Cơ', 3, 'passive', 'Chủ Nợ'),
  ('dcX2', 'dauco', 'Nhà Đầu Cơ', 2, 'passive', 'Khách Sộp'),
  ('dc1', 'dauco', 'Nhà Đầu Cơ', 3, 'passive', 'Môi Giới'),
  ('dcS2', 'dauco', 'Nhà Đầu Cơ', 3, 'active', 'Góp Vốn'),
  ('acX2', 'ancu', 'Thường Dân An Cư', 1, 'passive', 'Chủ Nhà'),
  ('ac1', 'ancu', 'Thường Dân An Cư', 2, 'passive', 'Mái Ấm'),
  ('ac2a', 'ancu', 'Thường Dân An Cư', 2, 'passive', 'Nhà Lâu Năm'),
  ('ac2b', 'ancu', 'Thường Dân An Cư', 2, 'passive', 'Đất Nhiều Màu'),
  ('ac3', 'ancu', 'Thường Dân An Cư', 3, 'passive', 'Sổ Hồng'),
  ('acU', 'ancu', 'Thường Dân An Cư', 4, 'passive', 'Phố Cổ'),
  ('acV', 'ancu', 'Thường Dân An Cư', 4, 'passive', 'Mặt Tiền'),
  ('acX1', 'ancu', 'Thường Dân An Cư', 3, 'passive', 'Sống Sót'),
  ('acS1', 'ancu', 'Thường Dân An Cư', 3, 'passive', 'Chung Cư Mini'),
  ('acS2', 'ancu', 'Thường Dân An Cư', 3, 'passive', 'Hàng Xóm Láng Giềng')
on conflict (skill_id) do update set branch = excluded.branch, branch_name = excluded.branch_name,
  tier = excluded.tier, kind = excluded.kind, name = excluded.name;
